---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reloader
  namespace: reloader
spec:
  template:
    spec:
      containers:
      - name: reloader
        image: ghcr.io/stakater/reloader:v1.0.152
        args:
        - --reload-strategy=annotations
