---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../apps/reloader/base

patches:
- path: deployment.reloader.yaml

transformers:
- labelTransformer.add-argocd-app-label.yaml
