---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- customResourceDefinition.undyingproxies.proxy.sfact.io.yaml
- deployment.undying-proxy.yaml
- namespace.undying-proxy.yaml
- podDisruptionBudget.undying-proxy.yaml
- podMonitoring.undying-proxy.yaml
- role.undying-proxy.yaml
- roleBinding.undying-proxy.yaml
- service.undying-proxy-tcp.yaml  # managed by operator, ArgoCD ignore spec
- service.undying-proxy-udp.yaml  # managed by operator, ArgoCD ignore spec
- serviceAccount.undying-proxy.yaml
