---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: undying-proxy
  namespace: undying-proxy
spec:
  template:
    spec:
      containers:
      - name: undying-proxy
        image: my-dev-registry.io/undying-proxy:v0.1.1
