---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: undying-proxy-234-234-234-234

resources:
- ../../../apps/undying-proxy/base

components:
- ../../../components/spot-node-pool

patches:
- path: deployment.undying-proxy.yaml
- path: service.undying-proxy-tcp.yaml
- path: service.undying-proxy-udp.yaml

transformers:
- labelTransformer.add-argocd-app-label.yaml
