---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector
      value:
        my-domain.com/node-pool-name: fastcpu-workloads
    - op: add
      path: /spec/template/spec/tolerations
      value:
      - key: my-domain.com/node-pool-name
        operator: Equal
        value: fastcpu-workloads
        effect: NoSchedule

